### ISSUE TITLE
Feature: Navigation from remote user's local profile to full profile on remote instance

### ISSUE THREAD

**Issue by wolfteeth** [ReticentJohn/Amaroq#1]
Currently the only way to view a remote user's full profile with Amaroq is:

- Visit the local version of their profile (usually incomplete)
- Tap the menu near the top of their profile
- Share
- Copy
- Open Safari and paste in URL

It would be nice to tap a UI element on the profile to open the remote version of their profile. In the web UI it's their profile pic - though I think a button or symbol would be clearer from a UI perspective.

It would be ideal to display it natively inside the app if there is an API method to grab a remote profile. If not, Amaroq could open it in Safari.

**Comment by ReticentJohn** [comment]
I am uncertain about the API's ability to show a remote profile, since its technically calling upon an entirely different instance, but I'll look into the potential of this. :3

If not, I don't see why there shouldn't be an ability to open in Safari. Thanks for the suggestion!

**Comment by bunnyhero** [comment]
yeah opening it in safari (or a built-in webview) is what i might expect anyway!
