### ISSUE TITLE
Feature: Autocomplete for most-used/followed users in toot composer

### ISSUE THREAD

**Issue by moritzheiber** [ReticentJohn/Amaroq#10]
The one feature I love the most in similar apps like Tweetbot or Tweetdeck is the ability to type `@` and have it auto-complete users I either mention frequently or are on my "following" list. I would absolutely love to have this feature in Amaroq as well.

I find myself very often to go through the steps of "* > My profile > Following > \<scroll-vigorously-until-I-find-the-account\> > Type the hamburger menu > Mention". I think this could be done easier/better :smiley:

**Comment by ReticentJohn** [comment]
I think there's value in being able to poll off the current user's following list - I was initially trying to think of how to do an overall user search but it was just too expensive. Perhaps we can start there (search for those that you're following) and then move towards implementing some logic that'll hold onto recent/frequent mentions.

**Comment by moritzheiber** [comment]
Exactly, small, incremental steps. And later Mastodon itself might actually have a more sophisticated API for searches one could use 😊

**Comment by kuro5hin** [comment]
Autocompleting @ for people I follow or who follow me would take care of, 99+% of my needs in autocompleting

**Comment by ReticentJohn** [comment]
Missed marking this in a commit, but v1.1.4 has this now. :)
