### ISSUE TITLE
🎺

### ISSUE THREAD

**Issue by ilianaw** [ReticentJohn/Amaroq#103]
🎺

![519b47b1432b0ea5](https://user-images.githubusercontent.com/52814/53613270-72db2180-3b8a-11e9-82cf-f818e61393b1.jpeg)

**Comment by tilda** [comment]
:trumpet:

**Comment by ReticentJohn** [comment]
v1.1.15 resolves this issue. You may need to switch between instances, logout/log back in, or toggle a notification setting on/off to get the app to resubscribe for push notifications. If this doesn’t work, deleting the app, restarting your device, and reinstalling should totally get you reset. Sorry for the inconvenience
