### ISSUE TITLE
Add support for polls

### ISSUE THREAD

**Issue by mathilde-blc** [ReticentJohn/Amaroq#107]
Hello,

ATM polls aren't displayed on the UI, we just can't see them and see only empty toots (if no other text on it).

Thanks in advance,

**Comment by mathilde-blc** [comment]
Nevermind, i switched to a somewhat more maintained app: Roma
https://www.pleroma.com/

**Comment by Krinkle** [comment]
@mthld This is still an issue in Amaroq could you re-open this for others benefit? Thanks 😊
