### ISSUE TITLE
Mastodon 2.8.0 compatibility

### ISSUE THREAD

**Issue by mathiasblc** [ReticentJohn/Amaroq#109]
Hello,

I'm opening this issue to track the changes made on the lasts Mastodon versions which needs to be implemented on Amaroq.

- CW size: #106 
- Polls: #107
- Reports: #108

I may be missing stuff, don't hesitate to add something.
Cheers,

**Comment by ReticentJohn** [comment]
You can track those issues individually, we don't need issues to track issues. :)
