### ISSUE TITLE
[Feature] Multi-account Support

### ISSUE THREAD

**Issue by asddsaz** [ReticentJohn/Amaroq#110]
**Feature**: Mult-account support.

**Why**?
I personally have two Mastadon accounts. 
One that is purely public and to gain a social presents. 
The other is an alias I utilize to follow projects and communicate.

Currently I am unware of any option to easily switch between the two.
My feature recommendation is to change this and add multi-account support.

**Comment by Krinkle** [comment]
As I understand it, this feature already exists.
