### ISSUE TITLE
[Feature] Add Support for Pleroma

### ISSUE THREAD

**Issue by ghbjklhv** [ReticentJohn/Amaroq#113]
**Feature**: Add Support for [Pleroma](https://pleroma.social/).
**What is Pleroma?**: [Pleroma](https://pleroma.social/) is a free software Mastadon compatible social network. It contains a strong focus on privacy and using low-resources.

__________________________

Want to support this issue? Post a bounty on it! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by mathilde-blc** [comment]
Hi,

This app isn’t maintained, i bet Pleroma won’t be supported. Check out Roma: 
https://www.pleroma.com/
