### ISSUE TITLE
"&nbsp;" not converted to non-breaking space

### ISSUE THREAD

**Issue by LudovicRousseau** [ReticentJohn/Amaroq#120]
If the text contains the HTML code &nbsp; then it is displayed as-is by Amaroq.
https://www.w3schools.com/html/html_entities.asp

For example with the toot https://social.bitcast.info/notice/4284089
See attached screen capture.
![Image-1](https://user-images.githubusercontent.com/398496/62833323-4c430b80-bc3d-11e9-8120-76a18373b802.jpg)

**Comment by skynebula** [comment]
Yep, same here, I often get that... :(
