### ISSUE TITLE
Following remote users leads to "http 404 raise_not_found" on mastodon instance

### ISSUE THREAD

**Issue by TheReal1604** [ReticentJohn/Amaroq#122]
If you try to follow a remote user in your notifications tab, this seems not to be possible. I see the following requests on the mastodon instance:

Amaroq request:
`2019-10-09T23:36:40.115292112Z [6a0d0304-f8eb-4576-b548-8cd1509b59c1] method=POST path=/api/v1/follows format=*/* controller=ApplicationController action=raise_not_found status=404 duration=8.53 view=0.00 db=0.34`

Webclient request:
`2019-10-09T23:37:08.565774005Z [f6caee63-b7e0-4b98-a37c-28a0eb09a712] method=POST path=/api/v1/accounts/25/follow format=html controller=Api::V1::AccountsController action=follow status=200 duration=40.38 view=0.83 db=9.41`

Maybe something changed in the mastodon api?

**Comment by hanscees** [comment]
same problem here: cant follow users on other instances with amaroq on ios13 (ipad)

**Comment by TheReal1604** [comment]
Just wanted to add, after some research, that this is caused by an api change on the mastodon site with version 3.0.0 and above.

**Comment by TheReal1604** [comment]
Aaaaand here is the PR there the change is located:

https://github.com/tootsuite/mastodon/pull/11800

**Comment by Nillevanille** [comment]
Hi, I wanted to add that I have also an issue with following people in the App. It is, however possible to add them on the Website. I think it is the same issue. I'm also using an ios  device.
