### ISSUE TITLE
Feature: French localization

### ISSUE THREAD

**Issue by pylapp** [ReticentJohn/Amaroq#128]
Bring french wording for the app

**Comment by pylapp** [comment]
Hey @ReticentJohn !

I have a question about the wording key "DON'T AWOO $350 PENALTY".

What is its aim? Could you bring more detail about that please?

Thanks

**Comment by ReticentJohn** [comment]
@pylapp it's an old meme, but it still checks out
![Screen Shot 2020-06-01 at 8 58 41 PM](https://user-images.githubusercontent.com/573400/83468569-1fb9e380-a44b-11ea-8eba-98c614a599a9.png)

When activated, it changes "toot" to "awoo" throughout the app - including posts themselves (see the NSString+Awoo category). Just a visual easter egg. :3

**Comment by pylapp** [comment]
Ahah ok, that's nice! I like that 👍

**Comment by pylapp** [comment]
Feature is ready with pull request #128.

Just boring conflicts to solve with locks and xconfig, but I cannot build the project on my side (#130) :)(
