### ISSUE TITLE
Bug: Xcode - Failed to install the requested application

### ISSUE THREAD

**Issue by pylapp** [ReticentJohn/Amaroq#130]
It seems there is an issue with Xcode and the management of bundle versions.
If fact even if the detail is filled in the Info.plist, the derived data is never updated.
Thus it is not possible to run the project in a simulator, and finally work on evolutions for the project :-/

Could you be nice to check that?

Thanks

<img width="411" alt="xcode" src="https://user-images.githubusercontent.com/7559007/83132339-89e82680-a0e1-11ea-870b-6ecfc9980f8f.png">

**Comment by pylapp** [comment]
@ReticentJohn Could you help me so solve this kind of issues please?

Thanks :)

**Comment by ReticentJohn** [comment]
Odd one @pylapp did you check the targets? Maybe one of them is missing a version and/or build number? 
![Screen Shot 2020-06-01 at 8 58 41 PM](https://user-images.githubusercontent.com/573400/83468465-d7022a80-a44a-11ea-9393-db9dce934e3b.png)

**Comment by johnmahlon** [comment]
I am also having this issue. Not sure what the problem is, but I'm looking into it as well.

**Comment by johnmahlon** [comment]
Ok, by manually updating the Bundle Version of `DireFloof/Supporting Files/Info.plist` and `Amaroq Push/Info.plist` to `1.0.0`, I get a new error.

![Screen Shot 2020-08-19 at 11 06 49 PM](https://user-images.githubusercontent.com/12173944/90715894-134f6500-e29b-11ea-8ab1-6b7c621fb7ea.png)

By clicking details:
```
This app could not be installed at this time.
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Could not install at this time.
Recovery Suggestion: Appex bundle at /Users/john/Library/Developer/CoreSimulator/Devices/2126153F-F009-4388-B620-63438F4F1745/data/Library/Caches/com.apple.mobile.installd.staging/temp.tEqtOE/extracted/Amaroq.app/PlugIns/com.keyboardfloofs.amarok.Amaroq-Push.appex with ID com.keyboardfloofs.amarok.Amaroq-Push does not have a CFBundleVersion key with a non-zero length string value in its Info.plist
--
Appex bundle at /Users/john/Library/Developer/CoreSimulator/Devices/2126153F-F009-4388-B620-63438F4F1745/data/Library/Caches/com.apple.mobile.installd.staging/temp.tEqtOE/extracted/Amaroq.app/PlugIns/com.keyboardfloofs.amarok.Amaroq-Push.appex with ID com.keyboardfloofs.amarok.Amaroq-Push does not have a CFBundleVersion key with a non-zero length string value in its Info.plist
Domain: MIInstallerErrorDomain
Code: 33
User Info: {
    FunctionName = "-[MIPluginKitPluginBundle validateBundleMetadataWithError:]";
    LegacyErrorString = MissingBundleVersion;
    SourceFileLine = 540;
}
--


System Information

macOS Version 10.15.6 (Build 19G2021)
Xcode 11.6 (16141)
```

This seems to be the same whether its on master or develop.

**Comment by pylapp** [comment]
@ReticentJohn Targets are good, and no entry is missing in the Info.plist files.
I have the same error as @johnmahlon :(

Do you have any news to share about this issue? Could it be related to certificates? Sometimes I got the error I mentioned, sometimes I got the error of @johnmahlon.

It is very blocking :(

If you have a running branch or commit, you could tell us which ones? Could it be one of the files listed in the .gitignore which is responsible of this mess? It may explain why you did not get the error.

Help will be very appreciated :)

**Comment by pylapp** [comment]
@ReticentJohn Could you tell use which version of Xcode you use?
