### ISSUE TITLE
Feature request: Open links in InApp-Browser instead of Safari

### ISSUE THREAD

**Issue by JanJastrow** [ReticentJohn/Amaroq#20]
Hi, very big fan of the app so far, but (coming from Tweetbot) I really miss one feature:

I would love it wehen links would open within the app and not send me to Safari.

(Could also be an option in the settings)

Edit: Okay, I just saw that this is already on your roadmap.

**Comment by ReticentJohn** [comment]
This is now available in v1.1.3 :D

**Comment by JanJastrow** [comment]
Makes the app so much better. Thanks.
