### ISSUE TITLE
Amaroq cannot access instance if the instance contains a content security header.

### ISSUE THREAD

**Issue by ka1210** [ReticentJohn/Amaroq#23]
Bug: Cannot access instance with content security header.

Today, for a brief time, https://social.tchncs.de was not accessible via Amaroq. After contacting the Administrator of the instance, I was informed that a content security header had to be removed in order for Amaroq to access the instance again.

Reference thread: https://social.tchncs.de/@milan/1420303

**Comment by ReticentJohn** [comment]
This thread provides no real context, sorry.

Additionally, there are plenty other instances running content security headers who are successfully connecting with Amaroq listed here: https://instances.mastodon.xyz/list
