### ISSUE TITLE
Bug: URL construction for "About Your Mastodon Instance"

### ISSUE THREAD

**Issue by pacohope** [ReticentJohn/Amaroq#25]
In the menu there's an option for "About Your Mastodon Instance". When you tap it, it loads a URL in Safari. The URL seems to be constructed badly. My instance is 'social.paco.to' and my account there is 'paco'. The link goes to https: // paco @ social.paco.to /about/more. On my iPhone, I get this warning:
![amaroq-phishing-warning](https://cloud.githubusercontent.com/assets/2158041/25576413/a64ebbaa-2e56-11e7-90b5-18a99d40af35.png)

I don't think there's any reason to have the username and the '@' in the URL.

**Comment by ReticentJohn** [comment]
This is a side-effect of including your username in the instance field when logging in, but I've been meaning to add logic to remove that. Thanks for reminding me.
