### ISSUE TITLE
Resize images on upload

### ISSUE THREAD

**Issue by tswast** [ReticentJohn/Amaroq#34]
We're having trouble uploading images to my instance.

![image](https://cloud.githubusercontent.com/assets/247555/26270783/c8228828-3cb2-11e7-8f39-17ff445e919a.png)

I believe this is because the image size is too big. The [server does not resize images](https://github.com/tootsuite/mastodon/issues/583) so this needs to be done client-side.

See related issue in Tusky: https://github.com/Vavassor/Tusky/issues/223

**Comment by ReticentJohn** [comment]
Until clients can know what the server limit is (and it can vary wildly) this is impossible to do client-side. You'll need to make sure your media abides the upload requirements for your instance

**Comment by tswast** [comment]
As far as I know the limits are not configurable. See: https://github.com/tootsuite/mastodon/issues/2252#issuecomment-296502151
