### ISSUE TITLE
App hangs sometimes when rotating a picture to landscape and swiping

### ISSUE THREAD

**Issue by noiob** [ReticentJohn/Amaroq#37]
When viewing a picture in landscape, which sometimes happens on accident sice the other UI doesn't rotate, and trying to dismiss it by swiping, the app sometimes stops responding to any input. This is on an iPhone 5 with the latest iOS 10

**Comment by ReticentJohn** [comment]
This should also now be fixed as of v1.1.7, please let me know if this problem persists!
