### ISSUE TITLE
media file extension missing when file is sent from app to server

### ISSUE THREAD

**Issue by lkhoydal** [ReticentJohn/Amaroq#4]
I've encountered that images doesn't show across instances because of missing mime type, and the info I've got from instance host so far is that media gets uploaded to server without file extension.

The instance I'm on is social.tchncs.de. I've uploaded a screenshot that I got from one who tried to see the photo.

![skjermbilde 2017-04-18 kl 23 36 29](https://cloud.githubusercontent.com/assets/17022196/25154202/ff0f302e-248f-11e7-8bdf-d1241df1d011.png)

**Comment by ReticentJohn** [comment]
While this can somewhat be remedied by sending the extension in the file name (and I'll be looking to do this, but it could take a couple weeks before it sees an App Store release, so this is better fixed on the other end), there are multiple issues going on server-side regarding correctly recognizing mime type. Amaroq has been sending the correct content type, and the API accepts it without error. It appears it fails at some point after the fact.

Possible related issue: https://github.com/tootsuite/mastodon/issues/2098
Possibly fixed as of ~45mins ago? https://github.com/tootsuite/mastodon/issues/1912

**Comment by lkhoydal** [comment]
If it is fixed server side, that is great. I missed that fix, but that is great. I just wanted to mention that it could be a problem, but it could well be already solved then. Thanks for the quick reply.
