### ISSUE TITLE
Allow access to the administration settings via Amaroq

### ISSUE THREAD

**Issue by wolfteeth** [ReticentJohn/Amaroq#44]
I'm an instance admin. I'd like to be able to view/edit instance settings via Amaroq - right now tapping "Administration" while on the preferences page just punts me back to the in-app account options.

Since this view is just the mobile web view, perhaps it could accept the Administration menu as a valid selection to stay in that view.

**Comment by ReticentJohn** [comment]
This is now in v1.1.9! :) (Forgot to include issue num in the commit my bad)
