### ISSUE TITLE
Feature request: Show low-res images while loading the high resolution

### ISSUE THREAD

**Issue by noiob** [ReticentJohn/Amaroq#47]
When I'm on a slow connection, I sometimes will have to wait a long time for an image to actually load, but the low-resolution preview only shows up cropped. It'd be really useful to be able to see the preview while the high-resolution image is loading instead of just the loading circle

**Comment by nightpool** [comment]
it feels like amaroq takes longer to load the high-res images then other apps, I don't know if it's due to this bug or for other reasons.

**Comment by noiob** [comment]
@nightpool I'm just talking about a UI change here, not performance

**Comment by nightpool** [comment]
Yes and I was talking about perceived performance, which I was acknowledging may just be a perceptual difference due to this UI bug

**Comment by noiob** [comment]
Ah, that makes sense, sorry

**Comment by ReticentJohn** [comment]
I believe I missed tagging this one in the release of 1.1.7, the media viewer should now be displaying the preview while the full-size image is downloaded. Will reopen if we're still having problems though.

**Comment by nightpool** [comment]
yep! this works great now.
