### ISSUE TITLE
Workflow question

### ISSUE THREAD

**Issue by mathias-b** [ReticentJohn/Amaroq#51]
Hello,

I just saw and Amaroq update on iOS devices but I don't see it here. Are you using this GitHub repository? Is it updated?

Thanks in advance,

🙇

**Comment by ReticentJohn** [comment]
All latest code will always be seen in Develop. Staging gets updated on deployment of TestFlight betas, Master gets updated on deployment to the App Store. Given the App Store updated at 1am my time, there is a bit of a delay, lol.

**Comment by mathias-b** [comment]
Thank you for the information!
