### ISSUE TITLE
No images shown

### ISSUE THREAD

**Issue by yrougy** [ReticentJohn/Amaroq#53]
Hey there,

I have an issue since a few weeks, no images are displayed, only a black rectangle (see attachement). <img width="375" alt="image" src="https://user-images.githubusercontent.com/2412199/30520254-4f6d8ce6-9baa-11e7-9ac0-04e0685205be.png">

I have uninstalled and reinstalled the app, but still have the issue.
- iPhone 7
- iOS 11
- Amaroq v1.1.5 (558)
On mastodon.cloud instance

Any ideas ?
Thanks 

Y.

**Comment by ReticentJohn** [comment]
Typically this indicates an issue with media federating from one instance to another. (in this case mastodon.xyz to mastodon.cloud) Or the mastodon.cloud instance is silencing media from mastodon.xyz, much like how pawoo media is silenced on mastodon.social (or was that lifted? I don't think it was). This is the reason I still opt to have Amaroq still send the media link in addition to the status text, as a fallback. Not ideal, but this has been an issue that I've been unable to work around on the client-side for months.

**Comment by yrougy** [comment]
Thanks for the explanation.
