### ISSUE TITLE
Status paragraphs truncated, emoji missing

### ISSUE THREAD

**Issue by nightpool** [ReticentJohn/Amaroq#65]
After updating to 1.1.8 this morning, I hit a bug with this status: https://toot.cafe/@sorin/99087458614656081

where it would render as so:

![fullsizerender 27](https://user-images.githubusercontent.com/233815/33411746-48fc2946-d555-11e7-9e36-b39b5637c013.jpg)

with only 1 emoji, and all paragraphs truncated to 1 line. 

Originally, it rendered correctly (albeit with no emoji). After clicking through to the detailed view, it flashed the emoji shortcodes and then switched to this rendering, which persisted after I backed out to the timeline view.

------

for reference, here's the status as it looks on mobile web:

![fullsizerender 28](https://user-images.githubusercontent.com/233815/33411747-4908cca0-d555-11e7-99a4-fc389ffac605.jpg)

**Comment by ReticentJohn** [comment]
Emojos will be the end of me... x3

**Comment by ReticentJohn** [comment]
![simulator screen shot - iphone x - 2017-11-29 at 23 02 26](https://user-images.githubusercontent.com/573400/33412491-a875704a-d559-11e7-88ee-2e80f8ae2e78.png)
![simulator screen shot - iphone x - 2017-11-29 at 23 02 21](https://user-images.githubusercontent.com/573400/33412492-a8821606-d559-11e7-92d3-897bfcb5a69e.png)

Appears it was a setup issue I missed when switching to ActiveLabel for link/username detection :( Thanks for catching this!
