### ISSUE TITLE
Text layout breaks probably because of custom Emojo

### ISSUE THREAD

**Issue by noiob** [ReticentJohn/Amaroq#66]
This toot: https://monsterpit.net/@daggertooth/99109171317715869
displays in Amaroq like this:
https://awoo.space/@noiob/99111009314995885 (can't add images on mobile, will fix later)

**Comment by fluffy-critter** [comment]
A much more prominent example: https://cybre.space/@unascribed/99242306472545190 renders as https://queer.party/@fluffy/99242326405940957

Also worth noting that the emoji names appear for a brief flash even if they’re cached locally.

**Comment by noiob** [comment]
I found an even worse example of emojos breaking:
https://cybre.space/@vantablack/99279214692770919
gets displayed as a single emojo or none depending on the view:
https://awoo.space/@noiob/99279700519471951

**Comment by ReticentJohn** [comment]
This is now in v1.1.9! :) (Forgot to include issue num in the commit my bad)
