### ISSUE TITLE
Feature Request: Support for excluding image URLs from being added to toots

### ISSUE THREAD

**Issue by BrodyB** [ReticentJohn/Amaroq#68]
Currently, adding images to a post will append a link to the resulting post text for each image, as is included by default when posting from the web. However, these links are entirely optional and clutter up toots.

It would be nice if there was a way to stop these links from appearing in posts made from Amaroq.

**Comment by ReticentJohn** [comment]
This is now in v1.1.9! :) (Forgot to include issue num in the commit my bad)
