### ISSUE TITLE
Feature request: Image viewer should allow rotation in landscape

### ISSUE THREAD

**Issue by xavbart** [ReticentJohn/Amaroq#7]
Application is designed to be used in portrait mode, that is fine and acceptable as a design choice.
But when one clicks to view images embedded in a toot (and gets in full screen image mode), one should be able to rotate device, to specifically view landscape images in portrait.
I understand this means allowing landscape mode app-wide and then locking all views but the ones for media viewing… But that'd be nice!

**Comment by ReticentJohn** [comment]
The app is actually already configured to allow this, I'm just having numerous issues with the third-party media viewer that I opted to use. It could either use some help, a replacement, or be written from scratch.
