### ISSUE TITLE
Feature Request: Edit profile in app

### ISSUE THREAD

**Issue by ThisIsMissEm** [ReticentJohn/Amaroq#75]
Presently to edit your profile, you have to log in again via a webview. There is an API in mastodon to allow this to be done natively, using the `/api/v1/accounts/update_credentials` endpoint (admittedly this isn't intuitively named)

I'm going to open an issue on the mastodon repo about creating a new API endpoint inline with that which is used by the web application. (likely, GET/PATCH/PUT `/api/v1/settings/profile`)

**Comment by ReticentJohn** [comment]
This is definitely on my list to do. Long ago, there was no API available at all to update account/profile info, but I've never circled back to properly account for what's now available. I believe there are several settings can be synced now too that I need to address.

**Comment by ThisIsMissEm** [comment]
Yup! I’ve created several tickets to address these missing APIs. I’d contribute to Amaroq, but unfortunately I don’t know objective c well enough
