### ISSUE TITLE
Awoo mode shouldn't replace "toot" with "awoo" if in a URL

### ISSUE THREAD

**Issue by sts10** [ReticentJohn/Amaroq#76]
With Awoo mode on, URLs with "toot" in them appear to be replaced with "awoo" ([example](https://octodon.social/@schlink/99815978368225073)). The URL then obviously points to a different destination, likely broken. This is particularly relevant since Mastodon's organizational name on Github is ["tootsuite"](https://github.com/tootsuite).

## Suggested Fix

Have Awoo mode check if the word "toot" is in a URL before replacing it. If it is doesn't replace it.

**Comment by ReticentJohn** [comment]
While this is on my list of things to do and I've trolled myself with Awoo mode when it comes to tootsuite countless times, Awoo mode has always been a gag and at this time I'm more focused on other features... I will gladly take PR's that will detect and ignore urls!
