### ISSUE TITLE
Thumbnails in image picker are often blank on iPhone X

### ISSUE THREAD

**Issue by bunnyhero** [ReticentJohn/Amaroq#77]
i think this is an issue with 3x screens. it's this bug https://github.com/guillermomuntaner/GMImagePicker/issues/84 . i tried the change that is posted in the comments, and it seems to fix it, but i didn't do any exhaustive tests.

**Comment by ReticentJohn** [comment]
Ahh I see, I’ll squeeze the fix into another beta tomorrow... I think we’re almost ready for an AppStore release after this! Thanks for spotting and investigating this bug, it really saves me some time <3
