### ISSUE TITLE
Feature request: allow user to "escape" detail view by swipe gesture from left

### ISSUE THREAD

**Issue by xavbart** [ReticentJohn/Amaroq#8]
Toot details view (that shows a conversation) has a top-right corner close button. Which is a very remote and small target for user's thumb. 
Tweetbot and Twitter official clients, for instance, will allow to swipe from left to return to timeline (go out of details). 
Such a similar gesture would be nice, as it allows the whole screen height to become the exit gesture's target. I understand that, as the "show details" glides from bottom, this might not be adapted in terms of UX feedback though.

**Comment by ReticentJohn** [comment]
Thanks for bringing this up :3
v1.1 will contain an overhaul of many of the navigation elements, including getting rid of the excessive modal view presentations in favor of the standard left/right "push"/"pop" navigation.
