### ISSUE TITLE
Switching between multiple instances sometimes causes all instance info to be lost

### ISSUE THREAD

**Issue by federicomenaquintero** [ReticentJohn/Amaroq#80]
I have a few instances registered in the app. Sometimes, switching quickly between instances causes all instance info to be lost, and I have to register all my accounts with the app again.

1. Register multiple instances in the app.

2. Use the app regularly.

3. Switch between instances: menu / My Instances / switch to another one

After (3), most of the time the app is fine and indeed shows you the instance you selected when you go back to the timelines.

But sometimes, after (3) the app loses all the instance information; it's as if you had never registered any instances with it. I have to give it an instance name and account information again.  Checking on the instances' web pages, I still have the old auth tokens for the app.

**Comment by rightmeow666** [comment]
@federicomenaquintero Yes, because the app doesn't support multiple accounts anyway. This is a duplicate to #81
