### ISSUE TITLE
Feature request: Improved support for multiple accounts

### ISSUE THREAD

**Issue by mkb** [ReticentJohn/Amaroq#81]
This is actually a request for multiple features. If you'd prefer I split it out into multiple issues I'd be happy to.

A few additions would make it much easier to use Amaroq with multiple Mastodon accounts. Many of these are inspired by TweetBot.

Most useful:
- Tap user icon in compose screen to post from other accounts
- Long-tap follow button to follow from other accounts
- Long-tap boost button to boost from other accounts

Also useful:
- Long-tap reply button to reply from other accounts
- Long-tap favorite button to favorite from other accounts

**Comment by berlincount** [comment]
I’d particularily be interested in the first feature myself, which might be an easy win.

The other would require way more UX logic changes, while the first one is limited to the compose screen.
