### ISSUE TITLE
Sharing Buttons

### ISSUE THREAD

**Issue by saschafoerster** [ReticentJohn/Amaroq#83]
Hi there, it would be great if Amaroq could support sharing buttons:
https://developer.apple.com/ios/human-interface-guidelines/extensions/sharing-and-actions/

**Comment by julianec** [comment]
This would be especially important when one tries to share an image via an app that removes the EXIF data like, especially GPS location.

**Comment by rightmeow666** [comment]
Isn't this already completed in the current release? @saschafoerster

**Comment by puresick** [comment]
> Isn't this already completed in the current release? @saschafoerster

@rightmeow666 no, in the latest release (v1.1.16), sharing buttons are not implemented.

**Comment by rightmeow666** [comment]
@puresick we have a share button for each toot under the `DWTimelineTableViewCell` class. Not sure if this is what you mean. Can you clarify?

**Comment by puresick** [comment]
Ah there might be a misunderstanding.
As fas as I understood the request by @saschafoerster, he wants to request the possibility to share from other apps to Amaroq.
For example if you are visiting a web page in safari and want to share it to Amaroq, you could use the share extension from Amaroq in the share menu.

Maybe @saschafoerster can clarify this if this was the case or if he wanted share buttons for toots from amaroq to other applications.

**Comment by saschafoerster** [comment]
@puresick Exactly! I want to share pictures and links TO Amaroq, not Toots from Amaroq to other services (which already works).

**Comment by rightmeow666** [comment]
I see what you guys are saying now, in that case, we can just reuse the design of `DWComposeViewController` (The toot editor / composer. You can find it by tapping the middle bottom tab)? @puresick

**Comment by puresick** [comment]
Yeah I think that would be more than sufficient! :)

**Comment by rightmeow666** [comment]
Here is a more helpful link for references: https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Share.html#//apple_ref/doc/uid/TP40014214-CH12-SW1
