### ISSUE TITLE
Amaroq crashes when shaking iPhone

### ISSUE THREAD

**Issue by MacLemon** [ReticentJohn/Amaroq#87]
Summary:
When shaking an iPhone, Amaroq crashes.

Steps to Reproduce:
Start typing a new toot, type something, select some text and delete it. Now shake your iPhone to invoke the undo dialog.

Expected Results:
Amaroq should ask to undo the text deletion.

Actual Results:
Amaroq crashes, loosing the draft toot content.

Regression:
n/a

Notes:
Sadly, my device does not seem to write any crash logs for this.

Device shaking may occur unintededly, for example when sitting in a bus that goes over a bump or while walking and taking a few quicker steps up the stairs, or to get into the underground.

Even if undo doesn't work, Amaroq should not crash and not loose what the user has been typing. (Save drafts.)

Version Information:
iOS 10.3.3
Amaroq v1.1.9 (631)

**Comment by rightmeow666** [comment]
Can't reproduce the crash anymore after iOS 10.
Even it is the case, this is likely an internal bug from iOS itself.

**Comment by MacLemon** [comment]
I rather suspect a problem with the undo manager, since undo is triggered by shaking.

**Comment by rightmeow666** [comment]
It's probably safe to close for now. @MacLemon
