### ISSUE TITLE
Media in direct messages does not work

### ISSUE THREAD

**Issue by codl** [ReticentJohn/Amaroq#9]
I'm not an amaroq user but I had someone on a remote server tell me that they can't see media in amaroq that I sent them in a direct message, they only get the standard not found message. They had to use the web interface to see it.

**Comment by ReticentJohn** [comment]
This appears to be a recent development on the server-side, I don't know if its to do with federation or what yet, but the media seems to appear after a while. I will continue to monitor and investigate what's possibly happening here but I'm afraid Amaroq is simply at the mercy of what the API hands it.
