### ISSUE TITLE
Feature request: cross-post to Twitter

### ISSUE THREAD

**Issue by karlbecker** [ReticentJohn/Amaroq#91]
Hello! Wanted to say nice job on the app so far.

I'd love to get more friends to move over to an open-source platform like Mastodon, but as my friend @jenweber [pointed out on Twitter](
https://twitter.com/jwwweber/status/1027737821627535360), cross-posting can be a helpful way to transition people over. 

I do iOS development, and I'm wondering two things:

1. Are you interested in having this functionality in Amaroq?
2. Anyone already working on it, or not yet?

I think it would have to involve individual users authorizing with the Twitter API from within Amaroq, but for those of us who have a decent Twitter following, this might be a fantastic way to move over full-time to a Mastodon client, rather than bouncing between the Twitter app and a Mastodon app.

Thoughts? Hope we can make it happen!

**Comment by ReticentJohn** [comment]
Hey @karlbecker - apologies for the late response. I personally was never planning on adding cross-posting support, but if you'd like to take on this feature you're more than welcome to!

My opinions around cross-posters in the past have been more centered on Twitter-based clients posting blindly to Mastodon being quite annoying, but the opposite is true here - I see value there.
